# Generated by Django 6.0.6 on 2026-06-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bd',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
