# Generated by Django 6.0.6 on 2026-06-24 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bd_content_bd_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='названия')),
            ],
            options={
                'verbose_name': 'рубрика',
                'verbose_name_plural': 'рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bd',
            options={'ordering': ['published'], 'verbose_name': 'объявление', 'verbose_name_plural': 'объявления'},
        ),
        migrations.AlterField(
            model_name='bd',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bd',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bd',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='bd',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.rubric'),
        ),
    ]
