# Generated by Django 6.0.6 on 2026-06-24 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rubric_alter_bd_options_alter_bd_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bd',
            options={},
        ),
        migrations.RemoveField(
            model_name='bd',
            name='rubric',
        ),
        migrations.AlterField(
            model_name='bd',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bd',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bd',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('price', models.FloatField()),
                ('published', models.DateTimeField(auto_now=True)),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.rubric')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
                'ordering': ['published'],
            },
        ),
    ]
