# Generated by Django 6.0.6 on 2026-08-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название мороженого')),
                ('flavor', models.CharField(choices=[('vanilla', 'Ванильное'), ('chocolate', 'Шоколадное'), ('strawberry', 'Клубничное'), ('pistachio', 'Фисташковое')], max_length=50, verbose_name='Вкус')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Мороженое',
                'verbose_name_plural': 'Мороженое',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
